// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Hero Coach",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Hero Coach",
            targets: ["AppModule"],
            bundleIdentifier: "code.sideProjects.hero-coach-v5",
            teamIdentifier: "Q5RF7T2UY7",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .speechRecognition(purposeString: "This app uses speech recognition to convert your spoken goals into text"),
                .microphone(purposeString: "This app uses speech recognition to convert your spoken goals into text")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/GoalClassificationModel.mlmodelc"),
                .copy("Resources/quotes.csv"),
                .copy("Resources/advice.csv")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)